name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_docs:
    # The type of runner that the job will run on
    name: Build documentation
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Build
        run: |
          make check-rules > check-rule-ids.log
          make all
      - name: Deploy to GitHub Pages
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Get App Installation Token
        run: |
          echo "This token is masked: ${TOKEN}"
        env:
          TOKEN: ${{ steps.get_token.outputs.app_token }}
      - name: Create issue
        env:
          TOKEN: ${{ steps.get_token.outputs.app_token }}
        run: |
            curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${TOKEN}" \
            https://api.github.com/repos/vadeg/restful-api-guidelines/issues \
            -d '{"title":"test issue"}'
